# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.4-SNAPSHOT
LABEL maintainer="dev@ballerina.io"

COPY namespace_openshift.balx /home/ballerina 

EXPOSE  9090
CMD ballerina run  namespace_openshift.balx
