# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.4-SNAPSHOT
LABEL maintainer="dev@ballerina.io"

COPY simple_route.balx /home/ballerina 

EXPOSE  9090
CMD ballerina run  simple_route.balx
